name: test project
on: 
  push:
    branches:
      - 'dev'
jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: install required modules
        run: pip install flask pylint pytest
      - name: run test
        run: pytest
      
