name: Linter and test
on: 
  push:
    branches:
      - 'dev'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: install required modules
        run: pip install pylint flask
      - name: run test
        run: pylint $(git ls-files '*.py')
  test:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: install required modules
        run: pip install pytest
      - name: run test
        run: pytest
  